#docker-composeで使用するバージョン
version: '3.8'

# dbデータの保存場所。(ホストからは見えない)
volumes:
  mysql-data:

services:
 #サービスの名前
  centos:
    build: .
    ports:
    - 8081:81
    - 8082:82
    - 8083:83
    - 8084:84
    - 8085:85
    - 8086:86
    - 8087:87
    - 8090:90
    - 8091:91
    - 18000:8000
    - 18001:8001
    - 18002:8002
    - 18003:8003
    - 18004:8004
    - 13000:3000
    volumes:
    - ./html:/var/www/html:cached
    - mysql-data:/var/lib/mysql
    working_dir: /var/www/html
    tty: true
    # platform: linux/x86_64 #CPUがm1の場合
    privileged: true  
    command: /sbin/init  