#docker-composeで使用するバージョン
version: '3.8'

# dbデータの保存場所。(ホストからは見えない)
volumes:
  mysql-data:

services:
 #サービスの名前
  centos:
    build: .
    ports:
    - 8281:81
    - 8282:82
    - 8283:83
    - 8284:84
    - 8285:85
    - 8286:86
    - 8287:87
    - 8290:90
    - 8291:91
    - 38000:8000
    - 38001:8001
    - 38002:8002
    - 38003:8003
    - 38004:8004
    - 33000:3000
    volumes:
    - ./html:/var/www/html:cached
    - mysql-data:/var/lib/mysql
    working_dir: /var/www/html
    tty: true
    platform: linux/x86_64 #CPUがm1の場合
    privileged: true  
    command: /sbin/init  